1. What is a Python library? Why do we use Python libraries? 


Ans:A collection of modules that are linked together is also known as a Python library.

Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language. They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without reinventing the wheel.


2. What is the difference between Numpy array an List? 


Ans:The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.


4. Write python code to access the first row of the following array? 
[[1, 2, 3, 4] 
[5, 6, 7, 8], 
[9, 10, 11, 12]] 


In [1]:
# Importing the NumPy library and aliasing it as 'np'
import numpy as np

# Creating a NumPy array 'arra_data' containing integers from 1 to 13 and reshaping it into a 4x4 matrix
arra_data = np.arange(1, 13).reshape((3, 4))

# Displaying a message indicating the original array will be printed
print("Original array:")

# Printing the original 4x4 array 'arra_data'
print(arra_data)

# Displaying a message indicating the extracted data (first row)
print("\nExtracted data: First row")

# Printing the first row of the 'arra_data' array using slicing
print(arra_data[0]) 



Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Extracted data: First row
[1 2 3 4]



6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [2]:
# Importing the NumPy library and aliasing it as 'np'
import numpy as np

# Creating a NumPy array 'arra_data' containing integers from 0 to 15 and reshaping it into a 4x4 matrix
arra_data = np.arange(1, 13).reshape((3, 4))

# Displaying a message indicating the original array will be printed
print("Original array:")

# Printing the original 4x4 array 'arra_data'
print(arra_data)

# Displaying a message indicating the extracted data (third and fourth elements of the first and second rows)
print("\nExtracted data: Third and fourth elements of the first and second rows")

# Using slicing to extract the first two rows and columns 2 and 3 (2:4 refers to 2nd and 3rd indices)
print(arra_data[0:2, 2:4])


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Extracted data: Third and fourth elements of the first and second rows
[[3 4]
 [7 8]]


7. How can you generate a random 3x3 matrix with values between 0 an 1? 


In [3]:
# Importing NumPy
import numpy as np  

# Using numpy.random.rand() to generate an array of random numbers of size (3, 3)
random_array = np.random.rand(3, 3)  

print(random_array)


[[0.98604612 0.94686103 0.67294497]
 [0.48932393 0.71347854 0.46047352]
 [0.82528187 0.37804803 0.82207763]]


8. Describe the difference between np.random.rand and np.radnom.randn? 


Ans:random. randn generates samples from the normal distribution, while numpy. random. rand from a uniform distribution (in the range [0,1)).


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [5]:
# importing python module named numpy
import numpy as np

# making a 3x4 array
gfg = np.array([[1, 2, 3, 4],
			   [5, 6, 7, 8],
			   [9, 10, 11, 12]])

# before transpose
print(gfg, end ='\n\n')

# after transpose
print(gfg.transpose()


SyntaxError: incomplete input (3845223116.py, line 13)

12.  Which function in Numpy can be use to swap the byte orer of an array?


Ans:byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.


 13.  What is the significance of the np.linalg.inv function? 


Ans : We use numpy. linalg. inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.


14. What does the np.reshape function on, an how is it use? 


Ans:reshape() function is used to create a new array of the same size (as the original array) but of different desired dimensions. reshape() function will create an array with the same number of elements as the original array, i.e. of the same size as that of the original array.



15. What is broacasting in Numpy? 


Ans:numpy.broadcast. The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.
